[".dot_cache/color-scripts"]
  url           = "https://gitlab.com/dwt1/shell-color-scripts"
  type          = "git-repo"
[".oh-my-zsh"]
  url           = "https://github.com/ohmyzsh/ohmyzsh"
  type          = "git-repo"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k"
